# Generated by Django 3.2.3 on 2021-06-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('author', models.CharField(max_length=20)),
                ('author_pic', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('pub_date', models.DateField()),
                ('pub_time', models.TimeField()),
                ('body', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
            ],
        ),
    ]
