# Generated by Django 3.2.3 on 2021-06-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='pub_time',
        ),
        migrations.AlterField(
            model_name='community',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
