# Generated by Django 3.2.3 on 2021-06-27 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20210627_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='pub_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
