# Generated by Django 3.2.3 on 2021-06-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20210627_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='date_or_time',
            field=models.BooleanField(default=True),
        ),
    ]
