# Generated by Django 3.2.3 on 2021-06-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_community_date_or_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='pub_time',
        ),
        migrations.AlterField(
            model_name='community',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
