# Generated by Django 3.2.3 on 2021-06-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20210628_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(help_text='Comment ID', primary_key=True, serialize=False)),
                ('author', models.CharField(default='익명', max_length=20, verbose_name='작성자')),
                ('content', models.TextField()),
                ('pub_datetime', models.DateTimeField()),
                ('origin_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
            ],
        ),
    ]
