# Generated by Django 3.2.3 on 2021-06-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_communitycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='pub_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
