# Generated by Django 3.2.3 on 2021-06-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20210629_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tag',
            field=models.CharField(default='공지', max_length=16),
        ),
    ]
