# Generated by Django 3.2.3 on 2021-06-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_community_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='date_or_time',
        ),
        migrations.AddField(
            model_name='community',
            name='notice_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
