# Generated by Django 3.2.3 on 2021-06-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20210630_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='today_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
