# Generated by Django 3.2.3 on 2021-07-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_alter_community_pub_dateonly'),
        ('community', '0016_auto_20210703_1829'),
    ]

    operations = [
    ]
