# Generated by Django 3.2.3 on 2021-07-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_communitycomment_author_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycomment',
            name='author_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
