# Generated by Django 3.2.3 on 2021-07-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_alter_communitycomment_author_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitycomment',
            name='author_thumb',
        ),
    ]
