# Generated by Django 3.2.3 on 2021-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_communitycomment_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitycomment',
            name='tag',
        ),
    ]
