# Generated by Django 3.2.3 on 2021-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=10, unique=True, verbose_name='닉네임')),
                ('joined_on', models.DateField(auto_now_add=True, verbose_name='가입일자')),
                ('user_thumbnail', models.ImageField(blank=True, default='./user_thumbnails/default-user.png', null=True, upload_to='user_thumbnails')),
                ('review_count', models.IntegerField(default=0)),
                ('average_time', models.CharField(default='0D 0H', max_length=20)),
                ('career', models.IntegerField(default=0)),
                ('stack', models.TextField(default='')),
                ('rating', models.FloatField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
