# Generated by Django 3.2.3 on 2021-07-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_thumbnail',
        ),
    ]
