# Generated by Django 3.2.3 on 2021-07-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_user_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
