# Generated by Django 3.2.3 on 2021-07-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_user_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='user_thumbnails'),
        ),
    ]
