# Generated by Django 3.2.3 on 2021-06-09 10:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=8, verbose_name='닉네임')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('show', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', help_text='비공개 여부', max_length=10)),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('PYTHON', 'PYTHON'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JS')], max_length=18)),
                ('bounty', models.IntegerField(default='0', verbose_name='현상금')),
                ('duedate', models.DateField(default='1900-01-01', verbose_name='마감기한')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='첨부파일')),
                ('body', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
