# Generated by Django 3.2.3 on 2021-06-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0002_alter_quest_bounty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='bounty',
            field=models.IntegerField(default='0', verbose_name='현상금'),
        ),
    ]
