# Generated by Django 3.2.3 on 2021-06-10 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0003_alter_quest_bounty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='duedate',
            field=models.DateField(default=datetime.date.today, verbose_name='마감기한'),
        ),
        migrations.CreateModel(
            name='QuestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=8)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanted.quest')),
            ],
        ),
    ]
