# Generated by Django 3.2.3 on 2021-06-22 09:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0005_auto_20210622_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quest',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PYTHON', 'PYTHON'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JS')], default=[], max_length=18),
        ),
    ]
