# Generated by Django 3.2.3 on 2021-06-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0006_auto_20210622_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='views',
        ),
        migrations.AddField(
            model_name='quest',
            name='remainingdays',
            field=models.IntegerField(default=0),
        ),
    ]
