# Generated by Django 3.2.3 on 2021-06-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0007_auto_20210627_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='status',
            field=models.CharField(choices=[('UNSOLVED', 'UNSOLVED'), ('SOLVING', 'SOLVING'), ('SOLVED', 'SOLVED'), ('EXPIRED', 'EXPIRED')], default='UNSOLVED', max_length=10),
        ),
    ]
