# Generated by Django 3.2.3 on 2021-06-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0008_alter_quest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='status',
            field=models.CharField(choices=[('UNSOLVED', 'UNSOLVED'), ('SOLVING', 'SOLVING'), ('SOLVED', 'SOLVED')], default='UNSOLVED', max_length=10),
        ),
    ]
