# Generated by Django 3.2.3 on 2021-06-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0010_quest_commentscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='태그명')),
            ],
        ),
        migrations.RemoveField(
            model_name='quest',
            name='commentscount',
        ),
        migrations.AlterField(
            model_name='questcomment',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wanted.quest'),
        ),
        migrations.AddField(
            model_name='quest',
            name='tag',
            field=models.ManyToManyField(default='', null=True, to='wanted.Tag', verbose_name='태그'),
        ),
    ]
