# Generated by Django 3.2.3 on 2021-06-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0011_auto_20210627_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='tag',
            field=models.ManyToManyField(blank=True, default='', null=True, to='wanted.Tag', verbose_name='태그'),
        ),
    ]
