# Generated by Django 3.2.3 on 2021-07-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0015_alter_quest_taglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('author', models.CharField(max_length=8)),
                ('body', models.TextField(verbose_name='내용')),
                ('code', models.TextField(default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='첨부파일')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='wanted.quest')),
            ],
        ),
    ]
