# Generated by Django 3.2.3 on 2021-07-15 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0021_auto_20210716_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='quest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='wanted.quest'),
        ),
    ]
